name: Trunk check
on:
  pull_request:
    branches: [$default-branch]
permissions: read-all

jobs:
  trunk_check:
    name: Trunk Code Quality Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
